server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: demo1
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/**
        - id: demo2
          uri: http://localhost:8082
          predicates:
            - Path=/api/v2/**














